[[redirects]]
  from = "http://login-asyncy.netlify.com/*"
  to = "https://login.asyncy.com/:splat"
  force = true

[[redirects]]
  from = "https://login-asyncy.netlify.com/*"
  to = "https://login.asyncy.com/:splat"
  force = true

[[redirects]]
  from = "http://login.asyncy.com/*"
  to = "https://login.asyncy.com/:splat"
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  query = { name = ":name", beta = ":beta" }
