[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  query = { name = ":name" }

[[redirects]]
  from = "http://login-asyncy.netlify.com/*"
  to = "https://login.asyncy.com/:splat"
  status = 301

[[redirects]]
  from = "http://login-asyncy.netlify.com/"
  to = "https://login.asyncy.com/"
  status = 301

[[redirects]]
  from = "https://login-asyncy.netlify.com/*"
  to = "https://login.asyncy.com/:splat"
  status = 301

[[redirects]]
  from = "https://login-asyncy.netlify.com/"
  to = "https://login.asyncy.com/"
  status = 301

[[redirects]]
  from = "http://login.asyncy.com/*"
  to = "https://login.asyncy.com/:splat"
  status = 301
  
